### ISSUE TITLE
takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by SanaullahOfficial** [cvqluu/simple_diarizer#5]
running a demo on google co-lab i am getting the following error, any idea how to resolve this, 

 File "/root/anaconda3/envs/simple/lib/python3.8/site-packages/speechbrain/pretrained/fetching.py", line 116, in fetch
    fetched_file = huggingface_hub.cached_download(url, use_auth_token)
TypeError: cached_download() takes 1 positional argument but 2 were given

**Comment by aconneau** [comment]
```
pip uninstall huggingface_hub && pip install huggingface_hub==0.7
```

**Comment by cvqluu** [comment]
This should be fixed now with https://github.com/cvqluu/simple_diarizer/commit/1a716c5c6f13aedbf01b4c350843c38f4a231b03

Issue seems to be fixed by allowing a newer version of speechbrain, which pulls from huggingface_hub in the updated way.

@SanaullahOfficial please feel free to try again with the colab notebook (which installs directly from the git repo).

I need to look into how to update the pypi package, but the colab notebook should now work
